spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://202.31.201.231:21/magic-conch?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: root

  data:
    web:
      pageable:
        one-indexed-parameters: true
  servlet:
    multipart:
      max-file-size: 500MB
      max-request-size: 500MB

server:
  port: 80

logging:
  level:
    com.filter: debug

custom:
  model-server-host: http://magic-conch-model:5000